[dev]
    functions = "./functions"
    framework = "#custom"
    targetPort = 8080
    command = "npm run dev"

[build]
    command = "npm run build"
    functions = "./functions"
    publish = "public"
    framework = "#custom"

[[plugins]]
    package = "netlify-plugin-inline-functions-env"

[template.environment]
  GOOGLE_SHEET_ID = "your googlesheet document id"
  GOOGLE_SERVICE_ACCOUNT_EMAIL = "your google service account email address"
  GOOGLE_CLIENT_PRIVATE_KEY = "your google service account private key"
  MAPBOX_ACCESS_TOKEN = "your mapbox access token"
  SUPABASE_KEY = "your supabase key"
  SUPABASE_URL = "your supabase url"
